version: 2.1
defaults: &defaults
  working_directory: ~/java-tracer
  docker:
    - image: circleci/openjdk:8u181-jdk

commands:
  checkout_utils:
    description: "Checkout various utilities"
    steps:
      - run:
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            cd ..
            git clone git@github.com:lumigo-io/common-resources.git
      - run:
          command: |
            cd ..
            git clone git@github.com:lumigo-io/utils.git
      - run:
          name: install python 3.7
          command: |
            sudo apt-get install -y python-software-properties
            sudo add-apt-repository --yes ppa:deadsnakes/ppa
            sudo apt-get update
            sudo apt-get install python3.7
            wget https://bootstrap.pypa.io/get-pip.py
            sudo python3.7 get-pip.py
            sudo python3.7 -m pip install --upgrade pip setuptools wheel
            sudo python3.7 -m pip install pipenv
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

  checkout_code:
    description: "Checkout code and install it"
    steps:
      - checkout
      - run:
          # Avoid annoying double runs after deploy.
          # See https://discuss.circleci.com/t/job-runs-even-when-tags-ignore-filter-is-triggered-when-combined-with-branches-only/20664
          name: Check if tagged
          command: |
            tags=$(git tag -l --points-at HEAD)
            echo "Tags $tags"
            if [[ ! -z "$tags" ]]
            then
              echo "A tagged commit, skip..."
              circleci step halt
            fi

      # Download and cache dependencies
      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - m2-

      - run:
          name: Install project dependencies of java tracer
          command: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}

workflows:
  test-deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
      - integration-test:
          filters:
            branches:
              ignore: master
          requires:
            - test
      - deploy:
          filters:
            branches:
              only: master

jobs:
  test:
    <<: *defaults
    steps:
      - checkout_code
      - run: ./scripts/checks.sh
      - run: bash <(curl -s https://codecov.io/bash)

  integration-test:
    <<: *defaults
    steps:
      - checkout_utils
      - checkout_code
      - run: sudo pip install awscli
      - run: ./scripts/ci_deploy.sh
      - run: cd ../integration-tests && npm i
      - run: sudo npm install -g recursive-install
      - run: cd ../integration-tests && ./scripts/prepare_env.sh
      - run: cd ../integration-tests && ./scripts/deploy.sh
      - run: cd ../integration-tests && npm run test

  deploy:
    <<: *defaults
    steps:
      - checkout_utils
      - checkout_code
      - run: ./scripts/bd_to_prod.sh
